[phases.setup]
nixpkgs = ["nodejs_20", "npm"]

[phases.build]
cmd = "npm ci --production --no-audit --no-fund"

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_CACHE = "/tmp/.npm"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
